"""
============================================================
 exemplos/docs_teoria.py
 Conteúdo teórico inline para cada exemplo, no formato DocView.
 Usado como fallback quando o PDF não está disponível,
 garantindo que a aba Teoria sempre exiba conteúdo completo.
============================================================
"""
from interface.doc_view import (
    _t, _s, _h, _b, _c, _li, _th, _tr, _eq, _sep, _bl,
)

DOCS_TEORIA: dict = {}

# ════════════════════════════════════════════════════════
#  AULA 04 — Transformações 2D
# ════════════════════════════════════════════════════════

DOCS_TEORIA["translacao"] = [
    _t("Translação 2D"),
    _s("Desloca um ponto somando um vetor (Tx, Ty) às coordenadas"),
    _sep(),
    _h("Conceito"),
    _b("Translação move um ponto ao somar um vetor de deslocamento T = (Tx, Ty). "
       "É a transformação mais simples: apenas muda a posição, "
       "preservando completamente a forma e o tamanho do objeto."),
    _bl(),
    _h("Fórmulas"),
    _eq("x' = x + Tx"),
    _eq("y' = y + Ty"),
    _bl(),
    _h("Exemplo Numérico"),
    _b("P = (30, 20)  e  T = (120, 80):"),
    _li("x' = 30 + 120 = 150"),
    _li("y' = 20 +  80 = 100"),
    _li("P' = (150, 100)  —  forma e tamanho preservados"),
    _bl(),
    _h("Representação Matricial (coords. homogêneas 3D)"),
    _b("Usar coordenadas homogêneas permite combinar translação com outras "
       "transformações numa única multiplicação de matrizes:"),
    _eq("| 1  0  Tx |   | x |   | x + Tx |"),
    _eq("| 0  1  Ty | × | y | = | y + Ty |"),
    _eq("| 0  0   1 |   | 1 |   |    1   |"),
    _bl(),
    _h("Propriedades"),
    _li("Isometria: preserva forma, tamanho, ângulos e distâncias"),
    _li("A origem NÃO é preservada (0,0) → (Tx, Ty)"),
    _li("Translação inversa: T(−Tx, −Ty)"),
    _li("Composição: T(a) seguida de T(b) = T(a+b)"),
    _li("Translação não comuta com escala nem rotação"),
    _bl(),
    _h("Código Python — NumPy"),
    _c("import numpy as np"),
    _c(""),
    _c("T = np.array([Tx, Ty])"),
    _c("P_novo = P + T"),
    _c(""),
    _c("# Coordenadas homogêneas:"),
    _c("M = np.array([[1, 0, Tx],"),
    _c("              [0, 1, Ty],"),
    _c("              [0, 0,  1]])"),
    _c("P_novo = (M @ np.array([x, y, 1]))[:2]"),
    _bl(),
    _h("Aplicações"),
    _li("Mover sprites e personagens em jogos 2D"),
    _li("Scroll de câmera em mapas e plataformers"),
    _li("Posicionar elementos em interfaces gráficas"),
    _li("Animações de entrada/saída de objetos"),
]

DOCS_TEORIA["escala"] = [
    _t("Escala 2D"),
    _s("Amplia, reduz ou espelha um objeto em relação à origem"),
    _sep(),
    _h("Conceito"),
    _b("Escala multiplica as coordenadas por fatores Ex e Ey. "
       "A origem permanece fixa durante a operação. "
       "Pode ser usada para ampliar, reduzir, distorcer ou espelhar."),
    _bl(),
    _h("Fórmulas"),
    _eq("x' = x × Ex"),
    _eq("y' = y × Ey"),
    _bl(),
    _h("Tipos de Escala"),
    _li("Ex = Ey > 1  →  Ampliação uniforme (zoom in)"),
    _li("Ex = Ey < 1  →  Redução uniforme (zoom out)"),
    _li("0 < Ex ≠ Ey  →  Distorção não-uniforme"),
    _li("Ex < 0       →  Reflexão no eixo Y"),
    _li("Ey < 0       →  Reflexão no eixo X"),
    _li("Ex = Ey = −1 →  Rotação de 180° em torno da origem"),
    _bl(),
    _h("Exemplo Numérico"),
    _b("Quadrado unitário com E = (2, 2):"),
    _li("A = (1, 1)  →  A' = (2, 2)"),
    _li("B = (3, 1)  →  B' = (6, 2)"),
    _li("C = (3, 3)  →  C' = (6, 6)"),
    _li("Área original = 4 u²,  área escalada = 16 u²  (× Ex × Ey)"),
    _bl(),
    _h("Matriz de Escala"),
    _eq("| Ex   0 |   | x |   | x × Ex |"),
    _eq("|  0  Ey | × | y | = | y × Ey |"),
    _bl(),
    _h("Escala em Ponto Arbitrário (cx, cy)"),
    _b("Para escalar em torno de um ponto P₀ = (cx, cy):"),
    _li("1. Transladar P₀ para a origem: P_rel = P − P₀"),
    _li("2. Aplicar escala: P_esc = S(Ex, Ey) · P_rel"),
    _li("3. Transladar de volta: P' = P_esc + P₀"),
    _bl(),
    _h("Código Python — NumPy"),
    _c("import numpy as np"),
    _c(""),
    _c("# Escala em torno da origem:"),
    _c("S = np.array([Ex, Ey])"),
    _c("P_novo = P * S"),
    _c(""),
    _c("# Escala em torno de (cx, cy):"),
    _c("c = np.array([cx, cy])"),
    _c("P_novo = np.array([Ex, Ey]) * (P - c) + c"),
    _bl(),
    _h("Aplicações"),
    _li("Zoom em mapas e imagens"),
    _li("Ajuste de tamanho de sprites e ícones"),
    _li("Animações de crescimento e pulsação"),
    _li("Espelhamento de personagens (virar à esquerda/direita)"),
]

DOCS_TEORIA["rotacao"] = [
    _t("Rotação 2D"),
    _s("Gira pontos em torno da origem por um ângulo θ"),
    _sep(),
    _h("Conceito"),
    _b("Rotação gira um ponto por um ângulo θ em torno da origem. "
       "É isométrica: preserva distâncias e ângulos, apenas muda a orientação do objeto."),
    _bl(),
    _h("Convenção de Sentido"),
    _li("CCW = Counter-Clockwise = Anti-horário (sentido matemático positivo)"),
    _li("CW  = Clockwise         = Horário"),
    _b("Em tela, o eixo Y cresce para baixo, portanto o sentido visual "
       "pode parecer oposto ao esperado na matemática clássica."),
    _bl(),
    _h("Fórmulas"),
    _eq("CCW:  x' =  x·cos θ − y·sin θ"),
    _eq("       y' =  x·sin θ + y·cos θ"),
    _bl(),
    _eq("CW:   x' =  x·cos θ + y·sin θ"),
    _eq("       y' = −x·sin θ + y·cos θ"),
    _bl(),
    _h("Exemplo Numérico"),
    _b("P = (1, 0),  rotacionar 90° CCW:"),
    _li("cos(90°) = 0,   sin(90°) = 1"),
    _li("x' = 1×0 − 0×1 = 0"),
    _li("y' = 1×1 + 0×0 = 1"),
    _li("P' = (0, 1) — subiu no eixo Y, como esperado"),
    _bl(),
    _h("Matrizes de Rotação"),
    _b("Anti-horário (CCW):"),
    _eq("R = | cos θ  −sin θ |"),
    _eq("    | sin θ   cos θ |"),
    _b("Horário (CW):"),
    _eq("R = |  cos θ  sin θ |"),
    _eq("    | −sin θ  cos θ |"),
    _bl(),
    _h("Propriedades"),
    _li("det(R) = 1 — preserva área (isometria direta)"),
    _li("R(θ)⁻¹ = R(−θ) = Rᵀ — inversa é a transposta"),
    _li("R(α)·R(β) = R(α+β) — composição soma ângulos"),
    _li("R(0°) = R(360°) = Identidade"),
    _li("Rotação comuta: R(α)·R(β) = R(β)·R(α)"),
    _bl(),
    _h("Rotação em Ponto Arbitrário (cx, cy)"),
    _li("1. Transladar P₀ para a origem: P_rel = P − P₀"),
    _li("2. Aplicar rotação: P_rot = R · P_rel"),
    _li("3. Transladar de volta: P' = P_rot + P₀"),
    _bl(),
    _h("Código Python — NumPy"),
    _c("import numpy as np, math"),
    _c(""),
    _c("t = math.radians(angulo_graus)"),
    _c("c, s = math.cos(t), math.sin(t)"),
    _c(""),
    _c("R_ccw = np.array([[ c, -s], [ s, c]])"),
    _c("R_cw  = np.array([[ c,  s], [-s, c]])"),
    _c(""),
    _c("P_novo = R_ccw @ P"),
]

DOCS_TEORIA["cisalhamento"] = [
    _t("Cisalhamento 2D  (Shearing)"),
    _s("Inclina o objeto proporcionalmente à outra coordenada"),
    _sep(),
    _h("Conceito"),
    _b("Cisalhamento desloca cada ponto proporcionalmente à sua outra coordenada. "
       "Produz efeito de inclinar o objeto — como um retângulo "
       "que vira um paralelogramo. Preserva a área, mas não os ângulos."),
    _bl(),
    _h("Fórmulas"),
    _eq("x' = x + Shx × y"),
    _eq("y' = y + Shy × x"),
    _bl(),
    _h("Tipos de Cisalhamento"),
    _li("Shx ≠ 0, Shy = 0  →  cisalha em X (inclina na horizontal)"),
    _li("Shx = 0, Shy ≠ 0  →  cisalha em Y (inclina na vertical)"),
    _li("Ambos ≠ 0          →  cisalha nos dois eixos"),
    _bl(),
    _h("Exemplo Numérico"),
    _b("Quadrado unitário com Shx = 0.5, Shy = 0:"),
    _li("A = (0, 0) → A' = (0.0, 0)   — base fixa (y=0)"),
    _li("B = (1, 0) → B' = (1.0, 0)   — base fixa (y=0)"),
    _li("C = (1, 1) → C' = (1.5, 1)   — desloca 0.5 em x"),
    _li("D = (0, 1) → D' = (0.5, 1)   — desloca 0.5 em x"),
    _b("Resultado: paralelogramo com base fixa."),
    _bl(),
    _h("Matriz de Cisalhamento (homogênea 3×3)"),
    _eq("|  1   Shx  0 |   | x |   | x + Shx·y |"),
    _eq("| Shy   1   0 | × | y | = | y + Shy·x |"),
    _eq("|  0    0   1 |   | 1 |   |     1     |"),
    _bl(),
    _h("Propriedades"),
    _li("Linhas paralelas permanecem paralelas"),
    _li("NÃO preserva ângulos nem distâncias"),
    _li("Preserva área (det da matriz de cisalhamento = 1)"),
    _li("Cisalhamento inverso: Shx → −Shx, Shy → −Shy"),
    _bl(),
    _h("Aplicações"),
    _li("Fontes itálicas — texto inclinado por cisalhamento em X"),
    _li("Perspectiva isométrica em jogos (view oblíqua)"),
    _li("Efeitos de sombra projetada 2D"),
    _bl(),
    _h("Código Python — NumPy"),
    _c("import numpy as np"),
    _c(""),
    _c("Shx, Shy = 0.5, 0.0"),
    _c("M = np.array([[1,   Shx, 0],"),
    _c("              [Shy, 1,   0],"),
    _c("              [0,   0,   1]])"),
    _c("P_novo = (M @ np.array([x, y, 1]))[:2]"),
]

# ════════════════════════════════════════════════════════
#  AULA 05 — Projeções e Recorte
# ════════════════════════════════════════════════════════

DOCS_TEORIA["window_viewport"] = [
    _t("Transformação Window-Viewport"),
    _s("Mapeia o espaço do mundo para coordenadas de tela"),
    _sep(),
    _h("Conceito"),
    _b("A janela (window) define a região do espaço do mundo que é visível. "
       "O viewport define onde na tela essa região aparece. "
       "A transformação mapeia proporcionalmente as coordenadas do mundo "
       "para as coordenadas de tela."),
    _bl(),
    _h("Fatores de Escala"),
    _eq("sx = (Vxmax − Vxmin) / (Wxmax − Wxmin)"),
    _eq("sy = (Vymax − Vymin) / (Wymax − Wymin)"),
    _bl(),
    _h("Mapeamento de Ponto"),
    _eq("Xv = Vxmin + (Xw − Wxmin) × sx"),
    _eq("Yv = Vymax − (Yw − Wymin) × sy   (Y invertido!)"),
    _bl(),
    _h("Por que Y é invertido?"),
    _b("Na matemática, Y cresce para cima. "
       "Na tela (pixels), Y cresce para baixo. "
       "Por isso Yv usa Vymax na subtração, "
       "o que inverte automaticamente o eixo."),
    _bl(),
    _h("Exemplo Numérico"),
    _b("Mundo: Wx=[−100, 100],  Wy=[−75, 75]"),
    _b("Tela:  Vx=[0, 800],     Vy=[0, 600]"),
    _li("sx = 800 / 200 = 4.0"),
    _li("sy = 600 / 150 = 4.0"),
    _li("P=(0, 0)    → tela (400, 300) — centro"),
    _li("P=(100, 75) → tela (800, 0)   — canto sup. dir."),
    _li("P=(−100,−75)→ tela (0, 600)   — canto inf. esq."),
    _bl(),
    _h("Efeitos Possíveis"),
    _li("Janela menor → mais zoom (sx e sy maiores)"),
    _li("Mover a janela → pan pelo mundo (sem alterar s)"),
    _li("Viewport proporcional diferente → esticar/achatar"),
    _li("Múltiplos viewports → split-screen"),
    _bl(),
    _h("Código Python"),
    _c("def world_to_vp(xw, yw,"),
    _c("                wxmin, wxmax, wymin, wymax,"),
    _c("                vxmin, vxmax, vymin, vymax):"),
    _c("    sx = (vxmax - vxmin) / (wxmax - wxmin)"),
    _c("    sy = (vymax - vymin) / (wymax - wymin)"),
    _c("    xv = int(vxmin + (xw - wxmin) * sx)"),
    _c("    yv = int(vymax - (yw - wymin) * sy)"),
    _c("    return xv, yv"),
]

DOCS_TEORIA["proj_ortogonal"] = [
    _t("Projeção Ortogonal"),
    _s("Visualização 3D com linhas de projeção paralelas"),
    _sep(),
    _h("Conceito"),
    _b("Remove uma dimensão, projetando pontos 3D num plano 2D. "
       "As linhas de projeção são paralelas entre si (não convergem). "
       "Não há perspectiva — objetos distantes não aparecem menores."),
    _bl(),
    _h("Fórmulas — Vista Frontal (plano XY)"),
    _eq("Xv = X × Escala"),
    _eq("Yv = Y × Escala   (Z é ignorado!)"),
    _bl(),
    _h("Tipos de Vista Ortogonal"),
    _li("Frontal  — projeta no plano XY  (ignora Z)"),
    _li("Lateral  — projeta no plano ZY  (ignora X)"),
    _li("Superior — projeta no plano XZ  (ignora Y)"),
    _b("Cada vista revela dimensões que as outras podem esconder."),
    _bl(),
    _h("Vantagens"),
    _li("Medidas preservadas — distâncias reais visíveis"),
    _li("Linhas paralelas no mundo permanecem paralelas"),
    _li("Simples de implementar — sem divisão por Z"),
    _li("Ideal para CAD, plantas e projetos técnicos"),
    _bl(),
    _h("Desvantagens"),
    _li("Não transmite sensação de profundidade"),
    _li("Difícil visualizar formas 3D complexas"),
    _li("Pode causar ambiguidade sobre orientação do objeto"),
    _bl(),
    _h("Comparação com Perspectiva"),
    _th("Aspecto | Ortogonal | Perspectiva"),
    _tr("Linhas paralelas | Permanecem paralelas | Convergem"),
    _tr("Distância afeta tamanho | Não | Sim"),
    _tr("Medidas preservadas | Sim | Não"),
    _tr("Uso típico | CAD, jogos iso | Jogos 3D, filmes"),
    _bl(),
    _h("Aplicações"),
    _li("CAD — plantas arquitetônicas e projetos mecânicos"),
    _li("Jogos isométricos: Diablo, SimCity, Age of Empires"),
    _li("Plantas técnicas: vista frontal, lateral e superior"),
    _bl(),
    _h("Código Python"),
    _c("def proj_ortho(x, y, z, escala, cx, cy):"),
    _c("    # Z é simplesmente descartado"),
    _c("    xv = int(cx + x * escala)"),
    _c("    yv = int(cy - y * escala)"),
    _c("    return xv, yv"),
]

DOCS_TEORIA["proj_perspectiva"] = [
    _t("Projeção em Perspectiva"),
    _s("Simula a visão humana — objetos distantes parecem menores"),
    _sep(),
    _h("Conceito"),
    _b("Objetos mais distantes aparecem proporcionalmente menores. "
       "Linhas paralelas no espaço 3D convergem para pontos de fuga. "
       "Produz imagens muito mais realistas do que projeção ortogonal."),
    _bl(),
    _h("Fórmula — Câmera Simples (1 ponto de fuga)"),
    _eq("Xv = d × X / Z"),
    _eq("Yv = d × Y / Z"),
    _b("d = distância focal (distância câmera → plano de projeção), "
       "Z = profundidade do ponto no espaço 3D."),
    _bl(),
    _h("Efeito da Distância Focal d"),
    _li("d grande  →  perspectiva fraca (parece ortogonal / teleobjetiva)"),
    _li("d pequeno →  perspectiva forte, distorção grande-angular"),
    _li("d → ∞     →  torna-se projeção ortogonal"),
    _b("Câmeras fotográficas: d equivale à distância focal da lente."),
    _bl(),
    _h("Comparação: Ortogonal × Perspectiva"),
    _th("Aspecto | Ortogonal | Perspectiva"),
    _tr("Linhas paralelas | Permanecem | Convergem"),
    _tr("Distância afeta tamanho | Não | Sim"),
    _tr("Ponto de fuga | Não tem | Sim"),
    _tr("Uso típico | CAD, jogos iso | Jogos 3D, filmes, VR"),
    _bl(),
    _h("Profundidade Mínima"),
    _b("Se Z ≈ 0, a divisão explode (ponto na câmera). "
       "Na prática usa-se um plano near (Z_near > 0) "
       "para evitar artefatos."),
    _bl(),
    _h("Código Python"),
    _c("def proj_persp(x, y, z, d, cx, cy, escala):"),
    _c("    dz = z + d   # dist. câmera ao ponto"),
    _c("    if abs(dz) < 0.001: dz = 0.001"),
    _c("    xv = int(cx + (d * x / dz) * escala)"),
    _c("    yv = int(cy - (d * y / dz) * escala)"),
    _c("    return xv, yv"),
    _bl(),
    _h("Perspectiva em Sistemas Completos"),
    _b("OpenGL/DirectX expressam perspectiva como matriz 4×4 "
       "aplicada a coordenadas homogêneas, seguida de divisão "
       "pela componente W. Isso permite pipeline GPU unificado."),
]

DOCS_TEORIA["clipping"] = [
    _t("Recorte de Segmentos"),
    _s("Algoritmo de Cohen-Sutherland"),
    _sep(),
    _h("Conceito"),
    _b("Recorte (clipping) elimina as partes de primitivas geométricas "
       "que estão fora da janela de visualização. "
       "Cohen-Sutherland usa um código de 4 bits para cada ponto, "
       "permitindo aceitar, rejeitar ou recortar segmentos eficientemente."),
    _bl(),
    _h("Código de Região (4 bits)"),
    _li("bit 3 (8) = TOPO     — y > ymax"),
    _li("bit 2 (4) = BASE     — y < ymin"),
    _li("bit 1 (2) = DIREITA  — x > xmax"),
    _li("bit 0 (1) = ESQUERDA — x < xmin"),
    _b("Região interior (visível): código 0000."),
    _bl(),
    _h("Grade de 9 Regiões"),
    _eq("1001  |  1000  |  1010"),
    _eq("0001  |  0000  |  0010"),
    _eq("0101  |  0100  |  0110"),
    _b("O código de cada região é a OR dos bits das bordas que o ponto viola."),
    _bl(),
    _h("Três Regras do Algoritmo"),
    _li("1. C1 = 0 E C2 = 0       →  ACEITAR (totalmente visível)"),
    _li("2. (C1 AND C2) ≠ 0       →  REJEITAR (totalmente fora)"),
    _li("3. Senão                  →  RECORTAR: calcular interseção e repetir"),
    _bl(),
    _h("Por que a Regra 2 funciona?"),
    _b("Se C1 AND C2 ≠ 0, ambos os pontos compartilham pelo menos "
       "um bit em comum — estão do mesmo lado de alguma borda. "
       "Logo o segmento não pode cruzar a janela."),
    _bl(),
    _h("Calculo da Interseção (Regra 3)"),
    _b("Escolhe-se o ponto com código ≠ 0 e calcula-se onde o segmento "
       "cruza a borda indicada pelo bit mais significativo do código:"),
    _li("TOPO:     xi = x1 + (x2−x1)×(ymax−y1)/(y2−y1)"),
    _li("BASE:     xi = x1 + (x2−x1)×(ymin−y1)/(y2−y1)"),
    _li("DIREITA:  yi = y1 + (y2−y1)×(xmax−x1)/(x2−x1)"),
    _li("ESQUERDA: yi = y1 + (y2−y1)×(xmin−x1)/(x2−x1)"),
    _bl(),
    _h("Vantagens"),
    _li("Aceite/rejeição trivial extremamente rápida"),
    _li("Eficiente quando maioria dos segmentos está fora"),
    _li("Base para algoritmos de clipping modernos"),
    _bl(),
    _h("Código Python"),
    _c("def cohen_code(x, y, xmin, xmax, ymin, ymax):"),
    _c("    c = 0"),
    _c("    if y > ymax: c |= 8  # TOPO"),
    _c("    if y < ymin: c |= 4  # BASE"),
    _c("    if x > xmax: c |= 2  # DIREITA"),
    _c("    if x < xmin: c |= 1  # ESQUERDA"),
    _c("    return c"),
    _c(""),
    _c("c1 = cohen_code(x1, y1, ...)"),
    _c("c2 = cohen_code(x2, y2, ...)"),
    _c("if c1 == 0 and c2 == 0:  # ACEITAR"),
    _c("elif c1 & c2 != 0:       # REJEITAR"),
    _c("else:                     # RECORTAR"),
]

# ════════════════════════════════════════════════════════
#  FUNDAMENTOS — Seno, Cosseno e Círculo
# ════════════════════════════════════════════════════════

DOCS_TEORIA["seno_cosseno"] = [
    _t("Seno e Cosseno"),
    _s("Funções trigonométricas e o círculo unitário"),
    _sep(),
    _h("O Círculo Unitário"),
    _b("Um círculo de raio 1 centrado na origem. Para qualquer ângulo θ, "
       "o ponto P na borda do círculo tem coordenadas:"),
    _eq("P = (cos θ,  sen θ)"),
    _b("Isso torna seno e cosseno as funções fundamentais de "
       "toda geometria circular e rotacional em computação gráfica."),
    _bl(),
    _h("Definições"),
    _li("cos θ  =  projeção do raio no eixo X  (componente horizontal)"),
    _li("sen θ  =  projeção do raio no eixo Y  (componente vertical)"),
    _li("O ângulo θ cresce no sentido anti-horário a partir do eixo X+"),
    _bl(),
    _h("Fórmulas Paramétricas"),
    _b("Para um ponto sobre um círculo de raio R centrado em (cx, cy):"),
    _eq("x = cx + R × cos(θ)"),
    _eq("y = cy + R × sen(θ)"),
    _b("Variando θ de 0 a 360° obtemos todos os pontos do círculo."),
    _bl(),
    _h("Identidade Fundamental"),
    _eq("sen²(θ) + cos²(θ) = 1"),
    _b("Decorre diretamente do Teorema de Pitágoras aplicado ao círculo "
       "unitário. É válida para qualquer ângulo."),
    _bl(),
    _h("Valores Notáveis"),
    _th("Ângulo (°) | sen | cos"),
    _tr("0°   | 0      | 1"),
    _tr("30°  | 0,500  | 0,866"),
    _tr("45°  | 0,707  | 0,707"),
    _tr("60°  | 0,866  | 0,500"),
    _tr("90°  | 1      | 0"),
    _tr("180° | 0      | −1"),
    _tr("270° | −1     | 0"),
    _tr("360° | 0      | 1"),
    _bl(),
    _h("Período e Simetria"),
    _li("Período: 360° (ou 2π radianos)"),
    _li("sen(−θ) = −sen(θ)  → função ímpar"),
    _li("cos(−θ) = cos(θ)   → função par"),
    _li("sen(90°−θ) = cos(θ) → cofunção"),
    _bl(),
    _h("Radianos × Graus"),
    _b("Python usa radianos internamente. A conversão é:"),
    _eq("radianos = graus × π / 180"),
    _eq("graus    = radianos × 180 / π"),
    _bl(),
    _h("Código Python"),
    _c("import math"),
    _c(""),
    _c("angulo_graus = 45"),
    _c("rad = math.radians(angulo_graus)"),
    _c(""),
    _c("s = math.sin(rad)   # seno"),
    _c("c = math.cos(rad)   # cosseno"),
    _c(""),
    _c("# Ponto sobre círculo de raio R"),
    _c("R = 100"),
    _c("x = cx + R * math.cos(rad)"),
    _c("y = cy - R * math.sin(rad)  # Y invertido em tela"),
    _bl(),
    _h("Aplicações em Computação Gráfica"),
    _li("Rotação de pontos e objetos 2D e 3D"),
    _li("Geração de círculos, elipses e arcos"),
    _li("Animações periódicas (pulsação, oscilação)"),
    _li("Cálculo de normais para iluminação"),
    _li("Transformações de câmera e ângulos de visão"),
]

DOCS_TEORIA["circulo"] = [
    _t("Gerando um Círculo"),
    _s("Construção paramétrica com seno e cosseno"),
    _sep(),
    _h("A Ideia Principal"),
    _b("Um círculo é o conjunto de todos os pontos equidistantes de um centro. "
       "Para gerá-lo programaticamente, usamos a parametrização trigonométrica: "
       "variamos o ângulo θ de 0 a 360° e calculamos cada ponto da borda."),
    _bl(),
    _h("Fórmula Paramétrica"),
    _eq("x(θ) = cx + R × cos(θ)"),
    _eq("y(θ) = cy − R × sen(θ)"),
    _b("Onde (cx, cy) é o centro, R é o raio e θ ∈ [0°, 360°]. "
       "O sinal negativo em y compensa o eixo Y invertido da tela (pixels crescem para baixo)."),
    _bl(),
    _h("Aproximação com N Pontos"),
    _b("Na prática, calculamos N pontos igualmente espaçados e os conectamos com segmentos de reta. "
       "Quanto maior N, mais suave o círculo:"),
    _eq("θᵢ = i × 360° / N,  para i = 0, 1, ..., N−1"),
    _li("N = 4  → quadrado inscrito"),
    _li("N = 6  → hexágono"),
    _li("N = 12 → dodecágono"),
    _li("N ≥ 32 → visualmente circular"),
    _bl(),
    _h("Código Python — NumPy"),
    _c("import math"),
    _c("import pygame"),
    _c(""),
    _c("def gerar_circulo(cx, cy, R, N=32):"),
    _c("    pontos = []"),
    _c("    for i in range(N):"),
    _c("        theta = math.radians(i * 360 / N)"),
    _c("        x = cx + R * math.cos(theta)"),
    _c("        y = cy - R * math.sin(theta)"),
    _c("        pontos.append((int(x), int(y)))"),
    _c("    return pontos"),
    _c(""),
    _c("pts = gerar_circulo(400, 300, 150, N=48)"),
    _c("pygame.draw.polygon(surface, cor, pts, 2)"),
    _bl(),
    _h("Quantidade de Pontos × Qualidade"),
    _b("Existe uma relação de compromisso entre qualidade visual e custo computacional. "
       "Para a maioria das aplicações, N = 32 é suficiente."),
    _th("N | Forma | Erro máximo"),
    _tr("4  | Quadrado | ~29% do raio"),
    _tr("8  | Octógono | ~7,6%"),
    _tr("16 | 16-gono  | ~1,9%"),
    _tr("32 | 32-gono  | ~0,5%"),
    _tr("64 | 64-gono  | ~0,1%"),
    _bl(),
    _h("Círculo vs. Elipse"),
    _b("Uma elipse usa raios diferentes para X e Y:"),
    _eq("x(θ) = cx + Rx × cos(θ)"),
    _eq("y(θ) = cy − Ry × sen(θ)"),
    _b("Basta alterar o raio separadamente em cada eixo."),
    _bl(),
    _h("Aplicações em Computação Gráfica"),
    _li("Desenho de círculos, arcos e elipses"),
    _li("Trajetórias circulares de objetos animados"),
    _li("Base para geração de polígonos regulares"),
    _li("Geração de esferas e cilindros em 3D"),
    _li("Cálculo de pontos em caminhos curvilíneos"),
]

# ════════════════════════════════════════════════════════
#  AULA 06 — Curvas de Bézier
# ════════════════════════════════════════════════════════

DOCS_TEORIA["bezier"] = [
    _t("Curvas de Bézier"),
    _s("Representação paramétrica de curvas suaves por pontos de controle"),
    _sep(),
    _h("O que é uma Curva de Bézier?"),
    _b("Uma curva de Bézier é uma curva paramétrica definida por um conjunto de "
       "pontos de controle P₀, P₁, ..., Pₙ. A curva passa pelos pontos extremos "
       "(P₀ e Pₙ) e é atraída pelos pontos intermediários, sem necessariamente "
       "passar por eles."),
    _bl(),
    _h("Fórmula Geral (Bernstein)"),
    _eq("B(t) = Σ  C(n,i) × (1−t)^(n−i) × t^i × Pᵢ,   t ∈ [0, 1]"),
    _b("Onde C(n,i) são os coeficientes binomiais e n é o grau da curva."),
    _bl(),
    _h("Casos Particulares"),
    _th("Grau | Pontos | Nome"),
    _tr("1 | P₀, P₁ | Segmento de reta"),
    _tr("2 | P₀, P₁, P₂ | Bézier quadrática"),
    _tr("3 | P₀, P₁, P₂, P₃ | Bézier cúbica"),
    _tr("n | P₀ ... Pₙ | Bézier de grau n"),
    _bl(),
    _h("Bézier Quadrática (grau 2)"),
    _eq("B(t) = (1−t)² P₀  +  2(1−t)t P₁  +  t² P₂"),
    _li("t=0 → ponto P₀ (início)"),
    _li("t=1 → ponto P₂ (fim)"),
    _li("P₁ atrai a curva como um 'imã'"),
    _bl(),
    _h("Bézier Cúbica (grau 3)"),
    _eq("B(t) = (1−t)³P₀ + 3(1−t)²t P₁ + 3(1−t)t²P₂ + t³P₃"),
    _b("Mais flexível — dois pontos de controle intermediários. "
       "É a base dos formatos SVG, PostScript e TrueType."),
    _bl(),
    _h("Algoritmo de De Casteljau"),
    _b("Método iterativo numericamente estável para calcular B(t) sem usar fórmulas "
       "explícitas de Bernstein. Funciona para qualquer grau:"),
    _li("1. Copie os pontos de controle em uma lista de trabalho"),
    _li("2. Repita: Pᵢ = (1−t)·Pᵢ + t·Pᵢ₊₁"),
    _li("3. Reduza a lista até sobrar 1 ponto"),
    _li("4. Esse ponto é B(t)"),
    _bl(),
    _h("Código Python — De Casteljau"),
    _c("def bezier_point(pontos, t):"),
    _c("    work = list(pontos)         # cópia"),
    _c("    n = len(work)"),
    _c("    while n > 1:"),
    _c("        for i in range(n - 1):"),
    _c("            work[i] = (1-t)*work[i] + t*work[i+1]"),
    _c("        n -= 1"),
    _c("    return work[0]              # B(t)"),
    _c(""),
    _c("# Gerar curva com 200 amostras:"),
    _c("curva = [bezier_point(pts, t/200) for t in range(201)]"),
    _bl(),
    _h("Propriedades Importantes"),
    _li("Interpolação nos extremos: a curva passa por P₀ e Pₙ"),
    _li("Tangente em P₀ é a direção P₀→P₁; em Pₙ é Pₙ₋₁→Pₙ"),
    _li("Convex hull: a curva fica dentro do polígono convexo dos controles"),
    _li("Invariante afim: translação, escala e rotação preservam a forma"),
    _li("Subdivisão: qualquer subcurva também é uma Bézier"),
    _bl(),
    _h("Limitação: Grau Cresce com Pontos"),
    _b("Com muitos pontos de controle, a curva de alto grau torna-se difícil de "
       "controlar localmente. A solução prática é usar B-Splines ou "
       "Bézier por partes (piecewise Bézier), onde múltiplas cúbicas são "
       "encadeadas com continuidade C¹ ou C²."),
    _bl(),
    _h("Aplicações em Computação Gráfica"),
    _li("Fontes vetoriais: TrueType e OpenType usam Bézier quadrática/cúbica"),
    _li("Curvas em editores vetoriais: Illustrator, Inkscape, Figma"),
    _li("Animação: ease-in/ease-out via curvas de timing"),
    _li("Paths em SVG: comandos Q (quadrática) e C (cúbica)"),
    _li("Modelagem 3D: superfícies de Bézier e NURBS"),
    _li("Trajetórias suaves de câmera e objetos em jogos"),
]

# ════════════════════════════════════════════════════════
#  AULA 08 — Visualização 3D, Cor e Iluminação
# ════════════════════════════════════════════════════════

DOCS_TEORIA["pipeline_3d"] = [
    _t("Pipeline de Visualização 3D"),
    _s("Do objeto 3D ao pixel na tela — passo a passo"),
    _sep(),
    _h("O que é o Pipeline 3D?"),
    _b("Imagine que você quer tirar uma foto de um cubo de brinquedo. "
       "Primeiro você coloca o cubo em algum lugar do quarto (mundo 3D). "
       "Depois aponta a câmera para ele. Depois o cubo aparece na foto (2D). "
       "O computador faz exatamente isso, mas com números e matrizes!"),
    _b("O Pipeline de Visualização 3D é a sequência de transformações que "
       "converte coordenadas de objetos 3D em pixels na tela 2D."),
    _bl(),
    _h("Os 5 Espaços do Pipeline"),
    _th("Espaço | O que é | Analogia"),
    _tr("Object Space | Coords. locais do objeto | O cubo no seu próprio centro"),
    _tr("World Space | Posição no cenário global | O cubo dentro do quarto"),
    _tr("Camera Space | Vista de onde a câmera está | O quarto visto pelo fotógrafo"),
    _tr("Clip Space | Caixa de recorte da câmera | O enquadramento da foto"),
    _tr("Screen Space | Pixels na tela | A foto impressa"),
    _bl(),
    _h("Passo 1 — Model Matrix (Object → World)"),
    _b("Posiciona, rotaciona e escala o objeto no mundo. "
       "É a combinação de Translação × Rotação × Escala que já estudamos:"),
    _eq("P_world = M_model × P_objeto"),
    _c("M_model = Translate × Rotate × Scale"),
    _bl(),
    _h("Passo 2 — View Matrix (World → Camera)"),
    _b("Transforma tudo para o ponto de vista da câmera. "
       "É como mover o mundo inteiro até que a câmera fique na origem olhando para Z−:"),
    _eq("P_cam = M_view × P_world"),
    _b("A View Matrix é construída com três vetores da câmera:"),
    _li("eye   — posição da câmera no mundo"),
    _li("center — ponto para onde a câmera olha"),
    _li("up    — vetor que aponta 'para cima' (geralmente Y+)"),
    _c("# LookAt simplificado"),
    _c("forward = normalize(center - eye)"),
    _c("right   = normalize(cross(forward, up))"),
    _c("up_real = cross(right, forward)"),
    _bl(),
    _h("Passo 3 — Projection Matrix (Camera → Clip)"),
    _b("Dois tipos de projeção (já estudados na Aula 05):"),
    _li("Ortogonal: objetos distantes NÃO ficam menores. Usado em CAD e jogos isométricos."),
    _li("Perspectiva: objetos distantes ficam menores. É como o olho humano enxerga."),
    _b("Projeção Perspectiva — parâmetros:"),
    _th("Parâmetro | Descrição"),
    _tr("FOV (Field of View) | Ângulo de abertura da câmera (ex: 60°)"),
    _tr("Aspect Ratio | Largura / Altura da tela"),
    _tr("Near (n) | Distância mínima visível"),
    _tr("Far (f) | Distância máxima visível"),
    _eq("x_proj = f * x / z      (fórmula simplificada)"),
    _bl(),
    _h("Passo 4 — Viewport Transform (NDC → Screen)"),
    _b("Após a projeção, as coordenadas ficam em NDC (Normalized Device Coordinates): "
       "tudo entre −1 e +1. A transformação viewport mapeia para pixels reais:"),
    _eq("x_tela = (x_ndc + 1) / 2 × largura"),
    _eq("y_tela = (1 − y_ndc) / 2 × altura"),
    _bl(),
    _h("A MVP Matrix — Tudo em Uma"),
    _b("Na prática, as três matrizes são multiplicadas em uma só antes de aplicar aos vértices. "
       "Isso economiza cálculo quando temos milhares de vértices:"),
    _eq("P_clip = M_proj × M_view × M_model × P_objeto"),
    _c("MVP = Projection × View × Model"),
    _c("for each vertex v:"),
    _c("    v_clip = MVP @ v"),
    _bl(),
    _h("Z-Buffer (Depth Buffer)"),
    _b("Como saber qual objeto está na frente do outro? "
       "O Z-Buffer guarda a profundidade de cada pixel já desenhado. "
       "Um novo pixel só substitui o atual se for MAIS PRÓXIMO da câmera:"),
    _li("Inicializa com Z = infinito (tudo muito distante)"),
    _li("Para cada triângulo: calcula Z de cada pixel"),
    _li("Compara com o Z guardado: se menor, pinta e atualiza"),
    _li("Resultado: objetos próximos tampam objetos distantes automaticamente"),
    _bl(),
    _h("Resumo do Pipeline"),
    _eq("Objeto → Model → World → View → Clip → NDC → Tela"),
    _b("Cada etapa é uma multiplicação de matriz. GPUs modernas fazem bilhões "
       "dessas multiplicações por segundo em paralelo!"),
]

DOCS_TEORIA["cores_iluminacao"] = [
    _t("Cor e Iluminação 3D"),
    _s("Como o computador calcula a cor de cada pixel de um objeto 3D"),
    _sep(),
    _h("O que é Cor para o Computador?"),
    _b("Pense no computador como um artista que mistura tinta. "
       "Ele usa três cores primárias de LUZ (não de tinta!): "
       "Vermelho, Verde e Azul — o modelo RGB."),
    _b("Cada canal vai de 0 (nada) a 255 (máximo). Misturando:"),
    _th("R | G | B | Cor resultante"),
    _tr("255 | 0   | 0   | Vermelho puro"),
    _tr("0   | 255 | 0   | Verde puro"),
    _tr("0   | 0   | 255 | Azul puro"),
    _tr("255 | 255 | 0   | Amarelo"),
    _tr("255 | 0   | 255 | Magenta"),
    _tr("0   | 255 | 255 | Ciano"),
    _tr("255 | 255 | 255 | Branco"),
    _tr("0   | 0   | 0   | Preto"),
    _bl(),
    _h("Outros Modelos de Cor"),
    _li("RGB — Vermelho, Verde, Azul. Padrão para telas e GPUs."),
    _li("HSV — Matiz (Hue), Saturação, Valor. Mais intuitivo para artistas."),
    _li("HSL — Matiz, Saturação, Luminosidade. Similar ao HSV."),
    _li("RGBA — RGB + canal Alpha (transparência). 0=invisível, 255=opaco."),
    _li("sRGB — RGB com correção gamma. Padrão para web e monitores."),
    _li("Linear RGB — sem correção gamma. Usado internamente em shaders."),
    _bl(),
    _h("O que é Iluminação em 3D?"),
    _b("Sem luz, tudo é preto. O modelo de iluminação calcula "
       "quanto de luz chega em cada ponto da superfície de um objeto, "
       "dependendo da posição da luz, do ângulo da superfície e do material."),
    _b("O modelo mais clássico é o Modelo de Phong (1975), "
       "que divide a luz em três componentes:"),
    _bl(),
    _h("Componente 1 — Luz Ambiente (Ambient)"),
    _b("É a luz que vem de todos os lados ao mesmo tempo, como a claridade do dia. "
       "Representa reflexões indiretas de luz no ambiente. "
       "Mesmo na sombra, um objeto ainda tem um pouquinho de cor:"),
    _eq("I_amb = Ka × La"),
    _li("Ka = coeficiente ambiente do material (0 a 1)"),
    _li("La = intensidade da luz ambiente"),
    _b("Analogia: o lado de trás de uma caixa em dia nublado — sem sol direto, mas visível."),
    _bl(),
    _h("Componente 2 — Luz Difusa (Diffuse)"),
    _b("É a luz que bate na superfície e espalha em todas as direções igualmente. "
       "Depende do ÂNGULO entre a luz e a normal da superfície (Lei de Lambert):"),
    _eq("I_dif = Kd × Ld × max(0,  N · L)"),
    _li("N = vetor normal da superfície (aponta para fora)"),
    _li("L = vetor da superfície até a fonte de luz"),
    _li("N · L = produto escalar (cosseno do ângulo)"),
    _li("Kd = cor difusa do material"),
    _b("Analogia: folha de papel iluminada de frente vs. de lado."),
    _bl(),
    _h("Componente 3 — Luz Especular (Specular)"),
    _b("É o brilho — reflexo direto da luz, como no espelho ou no metal. "
       "Depende do ângulo de visão do observador:"),
    _eq("R = 2(N · L)N − L      (vetor de reflexão)"),
    _eq("I_esp = Ks × Ls × max(0, R · V)^n"),
    _li("V = vetor da superfície até o observador (câmera)"),
    _li("R = direção de reflexão da luz"),
    _li("n = expoente de brilho (shininess): maior n = brilho mais concentrado"),
    _li("Ks = cor especular do material"),
    _b("Analogia: bolinha de isopor (sem brilho, n baixo) vs. bola de bilhar (brilho concentrado, n alto)."),
    _bl(),
    _h("Modelo Phong Completo"),
    _eq("I = Ka×La  +  Kd×Ld×(N·L)  +  Ks×Ls×(R·V)^n"),
    _b("A cor final de cada pixel é a soma das três componentes. "
       "Isso é calculado para cada vértice (Gouraud shading) "
       "ou para cada pixel (Phong shading)."),
    _bl(),
    _h("Tipos de Fontes de Luz"),
    _th("Tipo | Descrição | Analogia"),
    _tr("Direcional | Raios paralelos, sem posição | O sol"),
    _tr("Pontual | Irradia em todas direções | Uma lâmpada"),
    _tr("Spot | Cone de luz com direção | Lanterna"),
    _tr("Área | Superfície emissora | Softbox de estúdio"),
    _bl(),
    _h("Normal de Superfície"),
    _b("A normal é um vetor perpendicular à superfície. "
       "É fundamental para calcular iluminação. "
       "Para um triângulo com vértices A, B, C:"),
    _eq("N = normalize( (B−A) × (C−A) )"),
    _b("Onde × é o produto vetorial (cross product). "
       "Normais por vértice permitem suavização (smooth shading) — "
       "o arquivo OBJ armazena isso com o comando vn."),
    _bl(),
    _h("PBR — Physically Based Rendering"),
    _b("Modelo moderno (usado em jogos AAA e cinema). "
       "Em vez de Ka/Kd/Ks/Ns, usa parâmetros físicos reais:"),
    _li("Albedo — cor base do material"),
    _li("Metallic — o quanto é metálico (0=plástico, 1=metal)"),
    _li("Roughness — rugosidade (0=espelho, 1=completamente fosco)"),
    _li("AO — Ambient Occlusion (sombras em frestas)"),
    _li("Normal Map — detalhes de superfície sem polígonos extras"),
    _b("Esses valores são os mesmos do arquivo MTL com extensões PBR "
       "(Pr, Pm, norm, map_Ke) que o Blender exporta."),
]

DOCS_TEORIA["obj_formato"] = [
    _t("Formato OBJ Wavefront"),
    _s("O padrão universal para modelos 3D — do básico ao avançado"),
    _sep(),
    _h("O que é o formato OBJ?"),
    _b("Imagine um arquivo de texto que descreve como construir uma escultura 3D. "
       "O formato OBJ faz exatamente isso: cada linha é uma instrução. "
       "É como uma receita de bolo, mas para o computador montar um objeto 3D!"),
    _b("Criado pela Wavefront Technologies nos anos 1980 para o software "
       "Advanced Visualizer. Hoje é suportado por praticamente todo software 3D: "
       "Blender, Maya, 3ds Max, Unity, Unreal Engine, etc."),
    _bl(),
    _h("Características Principais"),
    _li("Formato de texto puro (ASCII) — pode abrir no Bloco de Notas"),
    _li("Sistema de coordenadas destro (right-handed), eixo Y para cima"),
    _li("Índices começam em 1 (não em 0 como Python!)"),
    _li("Dois arquivos: .obj (geometria) + .mtl (materiais)"),
    _li("Não suporta animação, armatures ou skinning"),
    _bl(),
    _h("Estrutura Básica de um OBJ"),
    _c("# Comentário (linha começa com #)"),
    _c("mtllib meu_arquivo.mtl   # referencia materiais"),
    _c(""),
    _c("# Vértices"),
    _c("v  0.0  0.0  0.0         # vértice 1: x y z"),
    _c("v  1.0  0.0  0.0         # vértice 2"),
    _c("v  1.0  1.0  0.0         # vértice 3"),
    _c("v  0.0  1.0  0.0         # vértice 4"),
    _c(""),
    _c("# Faces (triângulo e quadrilátero)"),
    _c("f 1 2 3                   # triângulo"),
    _c("f 1 2 3 4                 # quad (4 pontos)"),
    _bl(),
    _h("Os 4 Tipos de Vértice"),
    _th("Comando | Dados | Descrição"),
    _tr("v  | x y z [w] | Vértice geométrico (posição 3D)"),
    _tr("vt | u [v] [w] | Coordenada de textura UV"),
    _tr("vn | x y z     | Normal de vértice"),
    _tr("vp | u v [w]   | Vértice de parâmetro (curvas)"),
    _bl(),
    _h("O Comando de Face — f"),
    _b("A face define quais vértices formam cada polígono. "
       "Cada vértice pode ter até 3 índices: posição / textura / normal:"),
    _eq("f  v  /  vt  /  vn"),
    _c("f 1 2 3                  # só posição"),
    _c("f 1/1 2/2 3/3            # posição + textura"),
    _c("f 1/1/1 2/2/2 3/3/3      # posição + textura + normal"),
    _c("f 1//1 2//2 3//3         # posição + normal (sem textura)"),
    _b("Índices negativos referenciam a partir do fim da lista:"),
    _c("f -3 -2 -1               # últimos 3 vértices definidos"),
    _bl(),
    _h("Exemplo Completo — Cubo"),
    _c("# Cubo com material diferente em cada face"),
    _c("mtllib cubo.mtl"),
    _c("v 0 0 2   v 0 2 2   v 2 2 2   v 2 0 2"),
    _c("v 0 0 0   v 0 2 0   v 2 2 0   v 2 0 0"),
    _c(""),
    _c("g frente"),
    _c("usemtl vermelho"),
    _c("f 1 2 3 4"),
    _c(""),
    _c("g topo"),
    _c("usemtl azul"),
    _c("f 5 1 4 8"),
    _bl(),
    _h("Grupos e Objetos"),
    _th("Comando | Função"),
    _tr("o nome | Define um objeto (agrupa geometria relacionada)"),
    _tr("g nome | Define um grupo dentro de um objeto"),
    _tr("s 1    | Ativa smooth shading (suavização entre faces)"),
    _tr("s off  | Desativa smooth shading (faces facetadas)"),
    _tr("usemtl | Aplica material a faces seguintes"),
    _bl(),
    _h("O Arquivo MTL — Materiais"),
    _b("Cada material define como a superfície interage com a luz. "
       "Usa o Modelo de Phong com estas propriedades:"),
    _c("newmtl MeuMaterial         # nome do material"),
    _c("Ka 0.2 0.2 0.2            # cor ambiente (R G B)"),
    _c("Kd 0.8 0.4 0.1            # cor difusa  (laranja)"),
    _c("Ks 1.0 1.0 1.0            # cor especular (branco)"),
    _c("Ns 96.0                   # brilho (0=fosco, 1000=espelho)"),
    _c("d  1.0                    # opacidade (1=opaco, 0=invisível)"),
    _c("Ni 1.5                    # índice de refração (vidro=1.5)"),
    _c("illum 2                   # modelo: 2=Phong completo"),
    _c("map_Kd textura.png        # textura difusa"),
    _bl(),
    _h("Modelos de Iluminação MTL (illum)"),
    _th("Valor | Descrição"),
    _tr("0 | Cor constante, sem cálculo de luz"),
    _tr("1 | Ambient + Diffuse"),
    _tr("2 | Ambient + Diffuse + Specular (Phong completo)"),
    _tr("3 | Phong + reflexo com ray tracing"),
    _tr("4 | Phong + vidro transparente + ray tracing"),
    _tr("5 | Phong + reflexo Fresnel + ray tracing"),
    _bl(),
    _h("Extensões PBR (Physically Based Rendering)"),
    _b("Blender e softwares modernos adicionam propriedades PBR ao MTL:"),
    _c("Pr 0.5          # roughness (rugosidade: 0=espelho, 1=fosco)"),
    _c("Pm 1.0          # metallic (0=plástico, 1=metal)"),
    _c("Ke 1.0 0.5 0.0  # emissive (luz própria — laranja brilhante)"),
    _c("norm normal.png # normal map (detalhes de superfície)"),
    _c("map_Pm metal.png  # textura de metalicidade"),
    _c("map_Pr rough.png  # textura de rugosidade"),
    _bl(),
    _h("Lendo um OBJ em Python"),
    _c("def ler_obj(caminho):"),
    _c("    vertices, normais, uvs, faces = [], [], [], []"),
    _c("    with open(caminho) as f:"),
    _c("        for linha in f:"),
    _c("            p = linha.split()"),
    _c("            if not p: continue"),
    _c("            if p[0] == 'v':"),
    _c("                vertices.append((float(p[1]),"),
    _c("                                 float(p[2]),"),
    _c("                                 float(p[3])))"),
    _c("            elif p[0] == 'vn':"),
    _c("                normais.append((float(p[1]),"),
    _c("                                float(p[2]),"),
    _c("                                float(p[3])))"),
    _c("            elif p[0] == 'f':"),
    _c("                face = []"),
    _c("                for token in p[1:]:"),
    _c("                    idxs = token.split('/')"),
    _c("                    vi = int(idxs[0]) - 1  # -1: OBJ base 1"),
    _c("                    face.append(vi)"),
    _c("                faces.append(face)"),
    _c("    return vertices, normais, faces"),
    _bl(),
    _h("Limitações do Formato OBJ"),
    _li("Sem animação, skinning ou morph targets"),
    _li("Sem hierarquia de cenas ou nós"),
    _li("Arquivos grandes podem ser lentos (texto, não binário)"),
    _li("Sem suporte nativo a PBR (extensões não-padronizadas)"),
    _li("Alternativas modernas: glTF 2.0 (PBR nativo, animação, binário)"),
    _bl(),
    _h("Dica: OBJ vs glTF"),
    _b("OBJ é como o formato MP3 do 3D — simples, universal, funciona em todo lugar. "
       "glTF é como o formato AAC — mais moderno, eficiente e completo. "
       "Para aprender e projetos simples: OBJ. "
       "Para jogos e aplicações reais: glTF 2.0."),
    _bl(),
    _h("Coordenadas de Textura — UV Mapping"),
    _b("As coordenadas de textura (vt) mapeiam pixels de uma imagem 2D sobre a "
       "superfície 3D do modelo. O par (u, v) indica uma posição na textura, "
       "onde (0,0) é o canto inferior-esquerdo e (1,1) é o canto superior-direito:"),
    _c("vt 0.0  0.0    # canto inferior-esquerdo da textura"),
    _c("vt 1.0  0.0    # canto inferior-direito"),
    _c("vt 1.0  1.0    # canto superior-direito"),
    _c("vt 0.0  1.0    # canto superior-esquerdo"),
    _c(""),
    _c("f 1/1/1 2/2/1 3/3/1   # v/vt/vn por vértice"),
    _b("Cada vértice de uma face recebe um par UV independente, permitindo "
       "que a mesma posição 3D tenha texturas diferentes conforme a face."),
    _bl(),
    _h("Smooth Shading vs Flat Shading"),
    _b("O comando 's' controla como as normais são interpoladas entre as faces "
       "de um grupo, afetando a aparência da superfície:"),
    _th("Comando | Resultado visual"),
    _tr("s off (ou s 0) | Flat shading: cada face tem cor uniforme, arestas visiveis"),
    _tr("s 1            | Smooth shading: normais interpoladas, superficie suave"),
    _tr("s 2, s 3...    | Grupos de suavizacao separados (arestas entre grupos sao duras)"),
    _c("g cilindro_lateral"),
    _c("s 1            # suaviza o cilindro"),
    _c("f 1 2 3 ..."),
    _c(""),
    _c("g tampa"),
    _c("s off          # tampa fica facetada (plana)"),
    _c("f 10 11 12"),
    _b("No Flat Shading (usado neste visualizador), a normal é calculada uma vez "
       "por face usando o produto vetorial das suas arestas. No Smooth Shading, "
       "as normais dos vértices (vn) são interpoladas pela face, criando a "
       "ilusão de uma superfície curva mesmo com geometria facetada."),
    _bl(),
    _h("Triangulação de Polígonos"),
    _b("GPUs modernas só processam triângulos nativamente. Quads (4 vértices) "
       "e n-gons (5+ vértices) precisam ser decompostos em triângulos antes da "
       "renderização — processo chamado triangulação (ou tessellation):"),
    _c("# Quad original"),
    _c("f 1 2 3 4"),
    _c(""),
    _c("# Apos triangulacao (fan triangulation)"),
    _c("f 1 2 3"),
    _c("f 1 3 4"),
    _b("A triangulação por 'fan' usa o primeiro vértice como pivô e cria "
       "triângulos em leque. Para quads planos funciona perfeitamente; "
       "para n-gons côncavos pode gerar triângulos incorretos. "
       "O Blender usa algoritmos mais robustos (ear clipping) para esses casos."),
    _sep(),
    _t("Pipeline de Visualização 3D"),
    _s("Como o Leitor OBJ transforma dados em imagem na tela"),
    _sep(),
    _h("Visão Geral do Pipeline"),
    _b("Para exibir um modelo 3D na tela 2D, o computador executa uma sequência "
       "de transformações chamada pipeline de renderização. Cada etapa converte "
       "os dados de um espaço para outro:"),
    _eq("Objeto 3D -> Rotação -> Projeção -> Rasterização -> Tela"),
    _bl(),
    _h("Etapa 1 — Rotação (Transformação de Visão)"),
    _b("O visualizador usa duas rotações aplicadas em sequência sobre cada vértice. "
       "A rotação em X inclina o objeto para frente/trás; a rotação em Y gira "
       "em torno do eixo vertical:"),
    _eq("Rot_X: y' = y·cos(a) - z·sin(a)"),
    _eq("       z' = y·sin(a) + z·cos(a)"),
    _eq("Rot_Y: x' = x·cos(a) + z·sin(a)"),
    _eq("       z' =-x·sin(a) + z·cos(a)"),
    _b("As rotações são aplicadas ANTES da projeção para que o modelo "
       "aparente girar no espaço 3D ao mover o mouse."),
    _bl(),
    _h("Etapa 2 — Projeção Perspectiva"),
    _b("A projeção perspectiva simula como um olho ou câmera enxerga o mundo: "
       "objetos mais distantes parecem menores. A fórmula usa uma distância "
       "focal 'd' (distância do observador ao plano de projeção):"),
    _eq("xp = cx + (d * x / (z + d)) * escala"),
    _eq("yp = cy - (d * y / (z + d)) * escala"),
    _b("Quanto maior o z (mais distante), menor o divisor (z+d) fica perto de d, "
       "resultando em tamanho aparente reduzido. O sinal negativo em yp "
       "inverte o eixo Y (coordenadas de tela crescem para baixo)."),
    _bl(),
    _h("Etapa 3 — Painter's Algorithm"),
    _b("Para que faces próximas cubram as distantes (oclusão), o visualizador "
       "usa o Algoritmo do Pintor: ordenar todas as faces pela profundidade "
       "média (Z) e desenhar das mais distantes para as mais próximas:"),
    _c("# Calcular profundidade media de cada face"),
    _c("depth = media(z de cada vértice da face)"),
    _c(""),
    _c("# Ordenar: mais distante primeiro"),
    _c("faces.sort(key=lambda f: f.depth, reverse=True)"),
    _c(""),
    _c("# Desenhar em ordem (face proxima cobre a distante)"),
    _c("for face in faces:"),
    _c("    desenhar_poligono(face)"),
    _b("Limitação: o Painter's Algorithm pode falhar quando duas faces se "
       "intersectam ou formam ciclos de oclusão. Para esses casos, "
       "algoritmos mais robustos como BSP ou Z-Buffer são usados."),
    _bl(),
    _h("Etapa 4 — Cálculo da Normal de Face"),
    _b("A normal é um vetor perpendicular à face, essencial para o shading. "
       "É calculada com o produto vetorial (cross product) de duas arestas:"),
    _eq("e1 = v1 - v0"),
    _eq("e2 = v2 - v0"),
    _eq("N  = e1 x e2  (produto vetorial)"),
    _c("# Produto vetorial em Python"),
    _c("nx = e1y*e2z - e1z*e2y"),
    _c("ny = e1z*e2x - e1x*e2z"),
    _c("nz = e1x*e2y - e1y*e2x"),
    _b("A normal é calculada sobre os vértices já rotacionados (espaço de visão), "
       "garantindo que a direção da luz seja correta a cada frame."),
    _bl(),
    _h("Etapa 5 — Backface Culling"),
    _b("Uma face 'olha' para a câmera quando sua normal aponta na direção oposta "
       "ao observador. Com câmera no eixo -Z (olhando +Z), faces frontais têm "
       "componente Nz negativo após rotação. Faces traseiras são descartadas "
       "ou desenhadas com brilho reduzido:"),
    _eq("Se Nz < 0 -> face frontal (visível, calcula luz)"),
    _eq("Se Nz > 0 -> face traseira (oculta ou escura)"),
    _b("Backface culling reduz o número de faces desenhadas pela metade "
       "em objetos fechados (como uma esfera ou cubo), aumentando o desempenho."),
    _bl(),
    _h("Etapa 6 — Flat Shading (Modelo de Phong simplificado)"),
    _b("O flat shading calcula uma única cor por face com base no ângulo "
       "entre a normal da face e a direção da luz. Usa o Modelo de Phong "
       "com dois componentes:"),
    _eq("Intensidade = Ambiente + Difusa"),
    _eq("Difusa = max(0, N . L)"),
    _b("Onde N é a normal normalizada e L é o vetor unitário em direção à luz. "
       "O produto escalar (dot product) mede o cosseno do ângulo: quando a face "
       "está perpendicular à luz (N.L=1), recebe máxima iluminação; "
       "quando paralela (N.L=0), recebe apenas luz ambiente."),
    _c("# Cálculo em Python"),
    _c("dot   = max(0.0, nx*lx + ny*ly + nz*lz)"),
    _c("shade = AMBIENT + (1.0 - AMBIENT) * dot"),
    _c("cor_final = (r * shade, g * shade, b * shade)"),
    _bl(),
    _h("Rotação nos 3 Eixos"),
    _b("O visualizador suporta rotação independente em cada um dos 3 eixos. "
       "As matrizes de rotação para cada eixo são:"),
    _eq("Rot_X: y' = y*cos(a) - z*sin(a),  z' = y*sin(a) + z*cos(a)"),
    _eq("Rot_Y: x' = x*cos(a) + z*sin(a),  z' =-x*sin(a) + z*cos(a)"),
    _eq("Rot_Z: x' = x*cos(a) - y*sin(a),  y' = x*sin(a) + y*cos(a)"),
    _b("As rotações são aplicadas em sequência: primeiro X, depois Y, depois Z. "
       "A ordem importa — rotações não são comutativas: Rx*Ry != Ry*Rx. "
       "Isso significa que girar 45 graus em X e depois em Y produz um resultado "
       "diferente de girar 45 graus em Y e depois em X."),
    _bl(),
    _h("Modo Objeto vs Modo Câmera"),
    _b("O visualizador oferece dois modos de rotação com resultado visual idêntico, "
       "mas semântica diferente:"),
    _th("Modo | O que muda | Metáfora"),
    _tr("Objeto | Os vertices do modelo sao rotacionados | Girar o objeto na mao"),
    _tr("Camera | A camera orbita em torno da origem | Caminhar ao redor do objeto"),
    _b("Matematicamente, rotacionar o objeto +30 graus em Y é equivalente a "
       "rotacionar a câmera -30 graus em Y. No código:"),
    _c("# Modo Objeto: rotaciona os vertices"),
    _c("pts = rot_x(verts, angle_x)"),
    _c("pts = rot_y(pts,   angle_y)"),
    _c("pts = rot_z(pts,   angle_z)"),
    _c(""),
    _c("# Modo Camera: aplica rotacao inversa"),
    _c("pts = rot_x(verts, -cam_x)"),
    _c("pts = rot_y(pts,   -cam_y)"),
    _c("pts = rot_z(pts,   -cam_z)"),
    _b("No modo câmera, os eixos XYZ do mundo ficam absolutamente fixos enquanto "
       "o objeto parece estacionário e a câmera orbita. No modo objeto, o objeto "
       "gira dentro dos eixos fixos do mundo."),
    _bl(),
    _h("Modos de Visualização do Leitor OBJ"),
    _th("Modo | O que exibe | Uso"),
    _tr("Pontos    | Vertices como circulos; labels P1..Pn opcionais | Inspecionar geometria"),
    _tr("WireFrame | Arestas dos poligonos, cada grupo em cor diferente | Ver topologia"),
    _tr("Superficies | Faces + flat shading + cores por grupo | Ver forma"),
    _tr("Cores     | Igual Superficies mas com cores do arquivo MTL | Ver materiais"),
    _bl(),
    _h("Controles do Visualizador"),
    _th("Tecla / Botao | Acao"),
    _tr("Setas cima/baixo | Rotacionar no eixo ativo (sentido +/-)"),
    _tr("X / Y / Z        | Selecionar eixo de rotacao ativo"),
    _tr("HOME             | Zerar todos os angulos (objeto e camera)"),
    _tr("ESPACO           | Ligar/desligar rotacao automatica"),
    _tr("O                | Carregar proximo exemplo embutido"),
    _tr("Botao Objeto/Camera | Alternar quem rotaciona"),
    _tr("Botao Eixos 3D   | Mostrar/ocultar eixos XYZ na cena"),
    _tr("Botao + / -      | Aumentar/diminuir comprimento dos eixos"),
    _tr("Botao Labels      | Mostrar/ocultar labels P1..Pn (modo Pontos)"),
    _tr("Scroll mouse     | Rolar codigo OBJ/MTL no painel direito"),
    _bl(),
    _h("Normalização Automática do Modelo"),
    _b("Modelos OBJ podem ter escalas muito diferentes: uma xícara em centímetros "
       "ou um avião em metros. O visualizador normaliza automaticamente todos os "
       "modelos para caber num cubo [-1, +1]:"),
    _c("cx = (max_x + min_x) / 2          # centro do bounding box"),
    _c("ext = max(dx, dy, dz) / 2         # maior extensao"),
    _c("v_norm = ((x-cx)/ext, ...)        # normalizar"),
    _b("Isso garante que qualquer modelo seja exibido no centro da tela "
       "com tamanho adequado, independente da escala original."),
    _bl(),
    _h("Eixos 3D e Sistema de Coordenadas"),
    _b("O visualizador usa o sistema de coordenadas destro (right-handed), "
       "padrão no formato OBJ e em OpenGL:"),
    _li("Eixo X (vermelho): aponta para a direita"),
    _li("Eixo Y (verde): aponta para cima"),
    _li("Eixo Z (azul): aponta para fora da tela, em direcao ao observador"),
    _b("Os eixos são fixos no mundo — não rotacionam com o objeto. "
       "Partes positivas: seta e cor viva. "
       "Partes negativas: linha tracejada e cor escura (1/3 do brilho). "
       "Comprimento ajustável com os botões + e - no canto inferior."),
    _bl(),
    _h("Referência Rápida — Comandos OBJ"),
    _th("Comando | Significado"),
    _tr("# texto  | Comentario (ignorado pelo parser)"),
    _tr("v x y z  | Vertice geometrico 3D"),
    _tr("vt u v   | Coordenada de textura UV (0 a 1)"),
    _tr("vn x y z | Normal de vertice (vetor unitario)"),
    _tr("vp u v   | Vertice de parametro (curvas NURBS)"),
    _tr("f v1 v2 v3 | Face triangular (indices base 1)"),
    _tr("f v/t/n  | Face com textura e normal por vertice"),
    _tr("o nome   | Define objeto (agrupamento logico)"),
    _tr("g nome   | Define grupo de faces"),
    _tr("s 1/off  | Smooth shading ligado/desligado"),
    _tr("mtllib   | Referencia arquivo de materiais .mtl"),
    _tr("usemtl   | Aplica material as faces seguintes"),
    _bl(),
    _h("Referência Rápida — Comandos MTL"),
    _th("Comando | Significado"),
    _tr("newmtl nome | Define novo material"),
    _tr("Ka r g b    | Cor ambiente (luz indireta)"),
    _tr("Kd r g b    | Cor difusa (cor principal)"),
    _tr("Ks r g b    | Cor especular (reflexo de luz)"),
    _tr("Ns valor    | Brilho especular (0=fosco, 1000=espelho)"),
    _tr("d valor     | Opacidade (1=opaco, 0=invisivel)"),
    _tr("illum N     | Modelo de iluminacao (0-10)"),
    _tr("map_Kd img  | Textura difusa (imagem PNG/JPG)"),
    _tr("map_Ks img  | Textura especular"),
    _tr("norm img    | Normal map (detalhes de superficie)"),
]
