"""
Conteudo teorico rico para cada exemplo.
"""
from interface.teoria_view import (TITLE, SUB, TEXT, CODE, SEP,
                                    BLANK, INDENT, FORMULA)
import config as cfg

TEORIA_TRANSLACAO = [
    (TITLE,  "Translacao 2D", cfg.WHITE),
    (TEXT,   "Translacao move um ponto somando um vetor de deslocamento (Tx, Ty) "
             "as suas coordenadas. E a transformacao mais simples — "
             "apenas muda a posicao, preservando forma e tamanho."),
    (BLANK,  ""),
    (SEP,    ""),
    (SUB,    "Formula"),
    (TEXT,   "Dado ponto P = (x, y) e vetor T = (Tx, Ty):"),
    (FORMULA, "x' = x + Tx | y' = y + Ty"),
    (BLANK,  ""),
    (SEP,    ""),
    (SUB,    "Exemplo: triangulo com T = (120, 80)"),
    (INDENT, "A = (0, 0)   ->  A' = (120, 80)"),
    (INDENT, "B = (50, 0)  ->  B' = (170, 80)"),
    (INDENT, "C = (25, 40) ->  C' = (145, 120)"),
    (TEXT,   "Forma e tamanho preservados — apenas posicao muda."),
    (BLANK,  ""),
    (SEP,    ""),
    (SUB,    "Matriz Homogenea 3x3"),
    (FORMULA, "| 1  0  Tx |   | x |   | x+Tx |"),
    (FORMULA, "| 0  1  Ty | x | y | = | y+Ty |"),
    (FORMULA, "| 0  0   1 |   | 1 |   |   1  |"),
    (BLANK,  ""),
    (SEP,    ""),
    (SUB,    "Propriedades"),
    (INDENT, "Preserva forma e tamanho (isometria)"),
    (INDENT, "Preserva angulos e distancias"),
    (INDENT, "A origem NAO e preservada"),
    (INDENT, "Translacao inversa: T = (-Tx, -Ty)"),
    (INDENT, "Composicao: T(a) + T(b) = T(a+b)"),
    (BLANK,  ""),
    (SEP,    ""),
    (SUB,    "Codigo Python"),
    (CODE,   "import numpy as np\n\nT = np.array([120, 80])\nP = np.array([x, y])\nP_novo = P + T\n\n# Coordenadas homogeneas:\nM = np.array([[1, 0, 120],\n              [0, 1,  80],\n              [0, 0,   1]])\nP_h    = np.array([x, y, 1])\nP_novo = M @ P_h"),
    (BLANK,  ""),
    (SEP,    ""),
    (SUB,    "Aplicacoes"),
    (INDENT, "Mover sprites em jogos 2D"),
    (INDENT, "Scroll de camera em mapas"),
    (INDENT, "Posicionar elementos em interfaces"),
]

TEORIA_ESCALA = [
    (TITLE,  "Escala 2D", cfg.WHITE),
    (TEXT,   "Escala multiplica as coordenadas por fatores Ex e Ey. "
             "Pode ampliar, reduzir ou espelhar o objeto. "
             "A origem permanece fixa."),
    (BLANK,  ""),
    (SEP,    ""),
    (SUB,    "Formula"),
    (FORMULA, "x' = x * Ex | y' = y * Ey"),
    (BLANK,  ""),
    (SEP,    ""),
    (SUB,    "Tipos de Escala"),
    (INDENT, "Ex = Ey > 1  -> Ampliacao uniforme"),
    (INDENT, "Ex = Ey < 1  -> Reducao uniforme"),
    (INDENT, "Ex != Ey     -> Distorcao (nao-uniforme)"),
    (INDENT, "Ex < 0       -> Reflexao no eixo Y"),
    (INDENT, "Ey < 0       -> Reflexao no eixo X"),
    (BLANK,  ""),
    (SEP,    ""),
    (SUB,    "Exemplo: quadrado com E = (2, 2)"),
    (INDENT, "A = (1, 1) -> A' = (2, 2)"),
    (INDENT, "B = (3, 1) -> B' = (6, 2)"),
    (INDENT, "C = (3, 3) -> C' = (6, 6)"),
    (INDENT, "D = (1, 3) -> D' = (2, 6)"),
    (BLANK,  ""),
    (SEP,    ""),
    (SUB,    "Matriz de Escala"),
    (FORMULA, "| Ex   0 |   | x |   | x*Ex |"),
    (FORMULA, "|  0  Ey | x | y | = | y*Ey |"),
    (BLANK,  ""),
    (SEP,    ""),
    (SUB,    "Escala em Ponto Arbitrario"),
    (INDENT, "1. Transladar ponto para origem: T(-cx, -cy)"),
    (INDENT, "2. Aplicar escala: S(Ex, Ey)"),
    (INDENT, "3. Transladar de volta: T(cx, cy)"),
    (BLANK,  ""),
    (SEP,    ""),
    (SUB,    "Codigo Python"),
    (CODE,   "import numpy as np\n\nEx, Ey = 1.5, 2.0\nS = np.array([[Ex,  0],\n              [ 0, Ey]])\nP = np.array([x, y])\nP_novo = S @ P\n\n# Em torno de ponto (cx, cy):\ndef escala_ponto(P, Ex, Ey, cx, cy):\n    c = np.array([cx, cy])\n    return np.array([Ex, Ey]) * (P - c) + c"),
]

TEORIA_ROTACAO = [
    (TITLE,  "Rotacao 2D", cfg.WHITE),
    (TEXT,   "Rotacao gira um ponto em torno da origem por angulo theta. "
             "E isometrica: preserva distancias e angulos, "
             "apenas muda a orientacao do objeto."),
    (BLANK,  ""),
    (SEP,    ""),
    (SUB,    "Convencao de Sentido"),
    (INDENT, "CCW = Counter-Clockwise = Anti-horario (matematica)"),
    (INDENT, "CW  = Clockwise         = Horario (matematica)"),
    (TEXT,   "Em tela, o eixo Y e invertido, entao o sentido visual e oposto."),
    (BLANK,  ""),
    (SEP,    ""),
    (SUB,    "Formula CCW (anti-horario)"),
    (FORMULA, "x' = x*cos(t) - y*sin(t)"),
    (FORMULA, "y' = x*sin(t) + y*cos(t)"),
    (BLANK,  ""),
    (SUB,    "Formula CW (horario)"),
    (FORMULA, "x' = x*cos(t) + y*sin(t)"),
    (FORMULA, "y' = -x*sin(t) + y*cos(t)"),
    (BLANK,  ""),
    (SEP,    ""),
    (SUB,    "Exemplo: P=(1,0) rotacionado 90 graus CCW"),
    (INDENT, "cos(90) = 0,  sin(90) = 1"),
    (INDENT, "x' = 1*0 - 0*1 = 0"),
    (INDENT, "y' = 1*1 + 0*0 = 1"),
    (INDENT, "P' = (0, 1) — foi para cima, como esperado"),
    (BLANK,  ""),
    (SEP,    ""),
    (SUB,    "Matrizes de Rotacao"),
    (TEXT,   "CCW:"),
    (FORMULA, "R = | cos(t)  -sin(t) |"),
    (FORMULA, "    | sin(t)   cos(t) |"),
    (TEXT,   "CW:"),
    (FORMULA, "R = | cos(t)   sin(t) |"),
    (FORMULA, "    | -sin(t)  cos(t) |"),
    (BLANK,  ""),
    (SEP,    ""),
    (SUB,    "Propriedades"),
    (INDENT, "det(R) = 1 — preserva area (isometria direta)"),
    (INDENT, "R(t)^-1 = R(-t) = R^T — inversa e a transposta"),
    (INDENT, "R(a) * R(b) = R(a+b) — composicao soma angulos"),
    (INDENT, "R(0) = R(360) = Identidade"),
    (BLANK,  ""),
    (SEP,    ""),
    (SUB,    "Rotacao em Ponto Arbitrario P0=(cx,cy)"),
    (INDENT, "1. Transladar P0 para origem: P_rel = P - P0"),
    (INDENT, "2. Aplicar rotacao: P_rot = R * P_rel"),
    (INDENT, "3. Transladar de volta: P' = P_rot + P0"),
    (BLANK,  ""),
    (SEP,    ""),
    (SUB,    "Codigo Python"),
    (CODE,   "import numpy as np\nimport math\n\ndef rotacionar(P, graus, ccw=True):\n    t = math.radians(graus)\n    c, s = math.cos(t), math.sin(t)\n    if ccw:\n        R = np.array([[ c, -s],\n                      [ s,  c]])\n    else:\n        R = np.array([[ c,  s],\n                      [-s,  c]])\n    return R @ P\n\n# Exemplo: P=(3,0), 45 graus CCW\nP      = np.array([3.0, 0.0])\nP_novo = rotacionar(P, 45)\n# Resultado: (2.12, 2.12)"),
]

TEORIA_CISALHAMENTO = [
    (TITLE,  "Cisalhamento 2D (Shearing)", cfg.WHITE),
    (TEXT,   "Cisalhamento desloca pontos proporcionalmente a outra coordenada. "
             "Produz efeito de inclinar o objeto."),
    (BLANK,  ""),
    (SEP,    ""),
    (SUB,    "Formula"),
    (FORMULA, "x' = x + Shx * y"),
    (FORMULA, "y' = Shy * x + y"),
    (BLANK,  ""),
    (SEP,    ""),
    (SUB,    "Tipos"),
    (INDENT, "Shx != 0, Shy = 0 -> cisalha em X"),
    (INDENT, "Shx = 0, Shy != 0 -> cisalha em Y"),
    (INDENT, "Ambos != 0        -> cisalha nos dois eixos"),
    (BLANK,  ""),
    (SEP,    ""),
    (SUB,    "Exemplo: Shx=0.5 em quadrado"),
    (INDENT, "A = (0,0) -> A' = (0.0, 0)"),
    (INDENT, "B = (1,0) -> B' = (1.0, 0)"),
    (INDENT, "C = (1,1) -> C' = (1.5, 1)"),
    (INDENT, "D = (0,1) -> D' = (0.5, 1)"),
    (TEXT,   "Quadrado vira paralelogramo — base fixa."),
    (BLANK,  ""),
    (SEP,    ""),
    (SUB,    "Matriz de Cisalhamento"),
    (FORMULA, "|  1   Shx  0 |   | x |   | x+Shx*y |"),
    (FORMULA, "| Shy   1   0 | x | y | = | Shy*x+y |"),
    (FORMULA, "|  0    0   1 |   | 1 |   |    1    |"),
    (BLANK,  ""),
    (SEP,    ""),
    (SUB,    "Propriedades"),
    (INDENT, "Linhas paralelas permanecem paralelas"),
    (INDENT, "NAO preserva angulos nem distancias"),
    (INDENT, "Usado em fontes italicas e perspectiva isometrica"),
    (BLANK,  ""),
    (SEP,    ""),
    (SUB,    "Codigo Python"),
    (CODE,   "import numpy as np\n\ndef cisalhar(P, Shx=0, Shy=0):\n    M = np.array([[1,   Shx, 0],\n                  [Shy,   1, 0],\n                  [0,     0, 1]])\n    P_h = np.array([P[0], P[1], 1])\n    return (M @ P_h)[:2]\n\n# Shx=0.5, ponto (1,1)\nP      = np.array([1.0, 1.0])\nP_novo = cisalhar(P, Shx=0.5)\n# Resultado: (1.5, 1.0)"),
]

TEORIAS_MAP = {
    "translacao":    TEORIA_TRANSLACAO,
    "escala":        TEORIA_ESCALA,
    "rotacao":       TEORIA_ROTACAO,
    "cisalhamento":  TEORIA_CISALHAMENTO,
}
