"""
============================================================
 exemplos/aula04/opengl_exemplos/_teoria.py
 Conteúdo teórico dos exemplos PyOpenGL — embutido nativamente.
============================================================
"""
import sys, os
# Add parent paths so DocView import works
from interface.doc_view import DocView, DOCS, _b, _h, _s, _t, _c, _li, _th, _tr, _eq, _sep, _bl

# ── Documentos de teoria para cada exemplo ───────────────

DOCS["ex00_esfera"] = [
    _t("Exemplo 00 — Esfera 3D com PyOpenGL"),
    _s("Aula 04 — Computacao Grafica | UNIJUI 2026"),
    _sep(),
    _h("Objetivo"),
    _b("Criar uma janela OpenGL, configurar a camera em perspectiva e renderizar"
       " uma esfera 3D usando a funcao gluSphere da biblioteca GLU."),
    _bl(),
    _h("Estrutura do Projeto"),
    _c("PyOpenGL_Projeto_00/"),
    _c("  run.py               <- ponto de entrada"),
    _c("  requirements.txt     <- PyOpenGL PyOpenGL_accelerate"),
    _c("  src/"),
    _c("    exemplo.py         <- classe Exemplo (janela + callbacks)"),
    _c("    renderizador.py    <- classe Renderizador (gluSphere)"),
    _bl(),
    _h("Conceitos Essenciais"),
    _s("Double Buffering"),
    _b("GLUT_DOUBLE usa dois buffers de memoria. Enquanto um e exibido, o proximo"
       " frame e desenhado no outro. glutSwapBuffers() troca-os — elimina flickering."),
    _s("Teste de Profundidade (Z-Buffer)"),
    _b("GL_DEPTH_TEST: OpenGL descarta fragmentos cujo valor Z (profundidade) esta"
       " atras de fragmentos ja desenhados. Essencial para objetos 3D sobrepostos."),
    _s("Camera Perspectiva"),
    _b("gluPerspective(fov, aspect, near, far): define o frustum de visao."
       " gluLookAt(eye, at, up): posiciona a camera no espaco."),
    _bl(),
    _h("Pipeline OpenGL — Resumo"),
    _th("Etapa           |  Funcao                    |  Comando"),
    _tr("Inicializacao   |  Cria contexto OpenGL      |  glutInit()"),
    _tr("Display Mode    |  Define buffers ativos     |  glutInitDisplayMode()"),
    _tr("Janela          |  Cria janela na tela       |  glutCreateWindow()"),
    _tr("Profundidade    |  Habilita z-buffer         |  glEnable(GL_DEPTH_TEST)"),
    _tr("Projecao        |  Define frustum camera     |  gluPerspective()"),
    _tr("Camera          |  Posiciona ponto de vista  |  gluLookAt()"),
    _tr("Render          |  Limpa e redesenha         |  glClear() + glutSwapBuffers()"),
    _eq("sen²(t) + cos²(t) = 1"),
    _bl(),
    _h("gluSphere — Parametros"),
    _c("gluSphere(quadric, raio, fatias_lon, aneis_lat)"),
    _li("quadric: objeto gluNewQuadric() — gerencia o estilo de render"),
    _li("raio: tamanho da esfera no espaco do mundo"),
    _li("fatias_lon: subdivisoes longitudinais (meridianos) — mais = mais suave"),
    _li("aneis_lat: subdivisoes latitudinais (paralelos) — mais = mais suave"),
    _bl(),
    _h("Instalacao das Dependencias"),
    _c("pip install PyOpenGL PyOpenGL_accelerate"),
    _c(""),
    _c("# requirements.txt:"),
    _c("PyOpenGL"),
    _c("PyOpenGL_accelerate"),
]

DOCS["ex01_triangulo"] = [
    _t("Exemplo 01 — Triangulo Colorido"),
    _s("Aula 04 — Computacao Grafica | UNIJUI 2026"),
    _sep(),
    _h("Objetivo"),
    _b("Desenhar o primeiro primitivo OpenGL: um triangulo com vertices coloridos."
       " Introducao ao sistema de coordenadas 3D, glBegin/glEnd e interpolacao de cores."),
    _bl(),
    _h("Sistema de Coordenadas OpenGL"),
    _b("OpenGL usa um sistema destro (right-handed):"),
    _li("Eixo X: cresce para a direita"),
    _li("Eixo Y: cresce para cima"),
    _li("Eixo Z: cresce em direcao ao observador (para frente)"),
    _c("Origem: (0, 0, 0) — centro da cena"),
    _bl(),
    _h("Primitivos OpenGL — glBegin"),
    _th("Constante     |  Descricao               |  Vertices"),
    _tr("GL_POINTS     |  Pontos isolados          |  1 por ponto"),
    _tr("GL_LINES      |  Pares de linhas          |  2 por linha"),
    _tr("GL_LINE_LOOP  |  Poligono aberto          |  N vertices"),
    _tr("GL_TRIANGLES  |  Triangulos avulsos       |  3 por triangulo"),
    _tr("GL_QUADS      |  Quadrilateros            |  4 por quad"),
    _tr("GL_POLYGON    |  Poligono convexo         |  N vertices"),
    _eq("sen²(t) + cos²(t) = 1"),
    _bl(),
    _h("Interpolacao de Cores"),
    _b("Quando cada vertice tem uma cor diferente (glColor3f antes de glVertex3f),"
       " OpenGL interpola as cores automaticamente — efeito 'gradiente' no triangulo."),
    _c("glColor3f(r, g, b)   # valores de 0.0 a 1.0"),
    _c("glVertex3f(x, y, z)  # define o vertice COM a cor acima"),
    _bl(),
    _h("Camera Simples"),
    _c("glTranslatef(0, 0, -5)"),
    _b("Move a cena 5 unidades para tras (ou equivalente: afasta a camera 5 unidades)."
       " O observador fica na origem olhando para -Z."),
    _bl(),
    _h("Codigo Essencial"),
    _c("glBegin(GL_TRIANGLES)"),
    _c("  glColor3f(1, 0, 0)    # vermelho"),
    _c("  glVertex3f(-1, -1, 0) # vertice esquerdo"),
    _c("  glColor3f(0, 1, 0)    # verde"),
    _c("  glVertex3f( 1, -1, 0) # vertice direito"),
    _c("  glColor3f(0, 0, 1)    # azul"),
    _c("  glVertex3f( 0,  1, 0) # vertice topo"),
    _c("glEnd()"),
]

DOCS["ex02_formas"] = [
    _t("Exemplo 02 — Alternando Formas 3D"),
    _s("Aula 04 — Computacao Grafica | UNIJUI 2026"),
    _sep(),
    _h("Objetivo"),
    _b("Alternar entre 4 formas geometricas (triangulo, quadrado, cubo, piramide)"
       " usando teclado. Introducao ao padrao Renderizador e ao controle de estado."),
    _bl(),
    _h("Padrão Renderizador"),
    _b("Separa a logica de controle (Exemplo) da logica de desenho (Renderizador)."
       " O Exemplo gerencia o estado; o Renderizador apenas desenha."),
    _c("class Exemplo:"),
    _c("    def __init__(self):"),
    _c("        self.renderizador = Renderizador()"),
    _c("        self.formas = ['triangulo','quadrado','cubo','piramide']"),
    _c("        self.indice = 0"),
    _c(""),
    _c("class Renderizador:"),
    _c("    def desenhar_triangulo(self): ..."),
    _c("    def desenhar_quadrado(self):  ..."),
    _c("    def desenhar_cubo(self):      ..."),
    _bl(),
    _h("Formas Implementadas"),
    _th("Forma      |  Primitivo      |  Vertices  |  Caracteristica"),
    _tr("Triangulo  |  GL_TRIANGLES   |  3         |  Forma mais simples"),
    _tr("Quadrado   |  GL_QUADS       |  4         |  Poligono planar"),
    _tr("Cubo       |  GL_QUADS       |  4 por face|  So face traseira aqui"),
    _tr("Piramide   |  GL_TRIANGLES   |  3 por face|  Base + 4 faces laterais"),
    _eq("sen²(t) + cos²(t) = 1"),
    _bl(),
    _h("Controle de Estado com Indice"),
    _c("elif tecla == b'e':  # proximo"),
    _c("    self.indice = (self.indice + 1) % len(self.formas)"),
    _c("elif tecla == b'q':  # anterior"),
    _c("    self.indice = (self.indice - 1) % len(self.formas)"),
    _b("O operador % (modulo) garante que o indice volta ao inicio quando"
       " ultrapassa o ultimo elemento — ciclo circular."),
    _bl(),
    _h("GL_QUADS — Quadrilatero"),
    _c("glBegin(GL_QUADS)"),
    _c("  glColor3f(1, 1, 0)"),
    _c("  glVertex3f(-1, -1, 0)  # inferior esquerdo"),
    _c("  glVertex3f( 1, -1, 0)  # inferior direito"),
    _c("  glVertex3f( 1,  1, 0)  # superior direito"),
    _c("  glVertex3f(-1,  1, 0)  # superior esquerdo"),
    _c("glEnd()"),
    _li("Vertices devem ser em ordem anti-horaria (CCW) por convencao OpenGL"),
]

DOCS["ex03_grid_2d"] = [
    _t("Exemplo 03 — Grid e Movimentacao 2D"),
    _s("Aula 04 — Computacao Grafica | UNIJUI 2026"),
    _sep(),
    _h("Objetivo"),
    _b("Criar um grid de referencia 2D com projecao ortogonal, e mover/rotacionar"
       " formas geometricas com o teclado. Introducao as transformacoes em OpenGL."),
    _bl(),
    _h("Projecao Ortogonal 2D"),
    _c("glOrtho(-400, 400, -300, 300, -1, 1)"),
    _b("Define o volume de visao como um paralelepipedo. Nao ha perspectiva:"
       " objetos do mesmo tamanho parecem iguais independente da distancia."),
    _th("Parametro  |  Valor  |  Significado"),
    _tr("left       | -400    |  Borda esquerda do mundo"),
    _tr("right      |  400    |  Borda direita do mundo"),
    _tr("bottom     | -300    |  Borda inferior do mundo"),
    _tr("top        |  300    |  Borda superior do mundo"),
    _tr("near       |   -1    |  Plano de recorte proximo"),
    _tr("far        |    1    |  Plano de recorte distante"),
    _eq("sen²(t) + cos²(t) = 1"),
    _bl(),
    _h("Transformacoes de Modelo"),
    _c("glLoadIdentity()          # reset da matriz"),
    _c("glTranslatef(px, py, 0)   # posicionar objeto"),
    _c("glRotatef(angulo, 0,0,1)  # girar em torno do eixo Z"),
    _b("Ordem IMPORTA: translate depois de rotate gira em torno da origem."
       " Rotate depois de translate gira em torno do proprio eixo do objeto."),
    _bl(),
    _h("Formas 2D Disponiveis"),
    _th("Forma      |  Primitivo    |  Descricao"),
    _tr("Ponto      |  GL_POINTS    |  Ponto central"),
    _tr("Linha      |  GL_LINES     |  Linha horizontal"),
    _tr("Triangulo  |  GL_TRIANGLES |  Equilatero 50px"),
    _tr("Quadrado   |  GL_QUADS     |  100x100px"),
    _tr("Circulo    |  GL_POLYGON   |  N=100 vertices"),
    _tr("Elipse     |  GL_POLYGON   |  a=80, b=50"),
    _bl(),
    _h("Circulo via Seno/Cosseno"),
    _c("import math"),
    _c("glBegin(GL_POLYGON)"),
    _c("for i in range(100):"),
    _c("    ang = 2 * math.pi * i / 100"),
    _c("    x   = 50 * math.cos(ang)"),
    _c("    y   = 50 * math.sin(ang)"),
    _c("    glVertex2f(x, y)"),
    _c("glEnd()"),
    _bl(),
    _h("Teclas Especiais — glutSpecialFunc"),
    _c("def teclado_especial(self, tecla, x, y):"),
    _c("    if tecla == GLUT_KEY_LEFT:  self.pos_x -= 10"),
    _c("    if tecla == GLUT_KEY_RIGHT: self.pos_x += 10"),
    _c("    if tecla == GLUT_KEY_UP:    self.pos_y += 10"),
    _c("    if tecla == GLUT_KEY_DOWN:  self.pos_y -= 10"),
    _b("glutSpecialFunc captura setas e teclas funcionais (F1-F12)."
       " glutKeyboardFunc captura caracteres ASCII normais."),
]

DOCS["ex04_robo"] = [
    _t("Exemplo 04 — Robo com Hierarquia de Transformacoes"),
    _s("Aula 04 — Computacao Grafica | UNIJUI 2026"),
    _sep(),
    _h("Objetivo"),
    _b("Criar um robo com partes hierarquicas: base com translacao/rotacao,"
       " bracos que giram independentemente. Introducao ao uso de glPushMatrix"
       " e glPopMatrix para transformacoes hierarquicas."),
    _bl(),
    _h("Hierarquia de Transformacoes"),
    _b("glPushMatrix salva a matriz atual na pilha (stack)."
       " glPopMatrix restaura a ultima salva. Isso permite que cada"
       " parte do robo tenha seu proprio sistema de coordenadas local."),
    _c("glPushMatrix()           # salva estado global"),
    _c("  glTranslatef(tx,ty,0)  # move o robo"),
    _c("  glRotatef(a, 0,0,1)    # gira o corpo"),
    _c("  desenhar_base()        # usa coordenadas locais"),
    _c(""),
    _c("  glPushMatrix()         # salva estado do corpo"),
    _c("    glRotatef(a2, 0,0,1) # gira o braco"),
    _c("    desenhar_braco()     # coordenadas do braco"),
    _c("  glPopMatrix()          # restaura estado do corpo"),
    _c(""),
    _c("glPopMatrix()            # restaura estado global"),
    _bl(),
    _h("Estrutura do Projeto"),
    _c("PyOpenGL_Projeto_04/"),
    _c("  run.py"),
    _c("  src/"),
    _c("    exemplo.py      <- controle de estado e eventos"),
    _c("    renderizador.py <- desenho hierarquico do robo"),
    _c("    camera.py       <- configuracao de perspectiva"),
    _c("    entrada.py      <- mapeamento de teclas"),
    _bl(),
    _h("Separacao de Responsabilidades"),
    _th("Arquivo        |  Responsabilidade"),
    _tr("exemplo.py     |  Estado (posicao, angulos) e callbacks GLUT"),
    _tr("renderizador.py|  Desenho das pecas com glPushMatrix/glPopMatrix"),
    _tr("camera.py      |  gluPerspective + gluLookAt"),
    _tr("entrada.py     |  Mapeamento de teclas -> acoes"),
    _eq("sen²(t) + cos²(t) = 1"),
    _bl(),
    _h("Teclas do Robo"),
    _th("Tecla   |  Acao"),
    _tr("Seta    |  Translacao X/Y do robo"),
    _tr("R / T   |  Rotacao do corpo"),
    _tr("1 / 2   |  Translacao base esquerda/direita"),
    _tr("3 / 4   |  Rotacao braco 1"),
    _tr("5 / 6   |  Rotacao braco 2"),
    _tr("ESC     |  Fechar janela"),
    _bl(),
    _h("GL_LINE_LOOP — Contorno de Poligono"),
    _c("glBegin(GL_LINE_LOOP)"),
    _c("  glVertex2f(-w/3,  h/2)"),
    _c("  glVertex2f( w/3,  h/2)"),
    _c("  glVertex2f( w/2, -h/2)"),
    _c("  glVertex2f(-w/2, -h/2)"),
    _c("glEnd()"),
    _b("GL_LINE_LOOP conecta os vertices em sequencia e fecha automaticamente"
       " o ultimo com o primeiro — ideal para contornos de formas geometricas."),
]


def make_teoria_doc(key: str) -> DocView:
    """Cria e retorna um DocView para o documento de teoria do exemplo."""
    dv = DocView()
    dv._key    = key
    dv._blocks = DOCS.get(key, [])
    dv._loaded = True
    return dv
